export const PostType = [
  {
    value: "WorkFlow",
    label: "WorkFlow",
    image: "/assets/icons/workflow.svg",
  },
  {
    value: "Component",
    label: "Component",
    image: "/assets/icons/component.svg",
  },
  {
    value: "Knowledge",
    label: "Knowledge",
    image: "/assets/icons/knowledge.svg",
  },
];
export const modernTechnologies = [
  "React.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "GraphQL",
  "TypeScript",
  "Redux",
  "Tailwind CSS",
  "Docker",
  "Kubernetes",
  "Next.js",
  "Gatsby",
  "Flutter",
  "Electron",
  "TensorFlow",
  "Clerk",
  "NextAuth.js",
  "Auth0",
  "Firebase Authentication",
  "AWS Cognito",
  "Okta",
  "AuthRocket",
  "Stormpath",
  "Ping Identity",
  "Keycloak",
  "OAuth",
  "OpenID Connect",
  "JSON Web Tokens (JWT)",
  "bcrypt",
  "Passport.js",
];
